// ── ESER VERİSİ ──────────────────────────────────────────────────────────
// fotoUrl: 'images/AYV-XXXX.jpg' — görseli images/ klasörüne koyunca aktif olur
var ESERLER = [
  {
    id: "AYV-0001",
    ad: "Aya Triada Kilisesi",
    tur: "Dini Mimari",
    donem: "19. Yüzyıl",
    tescil: "1. Derece",
    mulkiyet: "Vakıf",
    koruma: "Orta",
    durum: "Onaylı",
    malzeme: "Taş, Ahşap",
    islevOzgun: "Kilise",
    islevGuncel: "Kullanım Dışı",
    mahalle: "Kemalpaşa",
    lat: 39.3205, lng: 26.6935,
    aciklama: "Geç Osmanlı döneminde inşa edilmiş Rum Ortodoks kilisesi. Üç nefli bazilikal planlı yapı, 19. yüzyıl taş işçiliğinin bölgedeki önemli örneklerinden biridir.",
    fotoBg: "linear-gradient(160deg,#3a2818,#5a3828)",
    fotoUrl: "images/AYV-0001.jpg"
  },
  {
    id: "AYV-0002",
    ad: "Saatli Cami (Agios Yannis)",
    tur: "Dini Mimari",
    donem: "19. Yüzyıl",
    tescil: "1. Derece",
    mulkiyet: "Vakıf",
    koruma: "İyi",
    durum: "Onaylı",
    malzeme: "Taş",
    islevOzgun: "Kilise",
    islevGuncel: "Cami",
    mahalle: "Cumhuriyet",
    lat: 39.3195, lng: 26.6962,
    aciklama: "Rum döneminden kalma Agios Yannis Kilisesi, Cumhuriyet sonrasında camiye dönüştürülmüştür. Saat kulesi Ayvalık siluetinin belirleyici ögelerinden biridir.",
    fotoBg: "linear-gradient(160deg,#1a2a1a,#2a4a2a)",
    fotoUrl: "images/AYV-0002.jpg"
  },
  {
    id: "AYV-0003",
    ad: "Hamidiye Camii",
    tur: "Dini Mimari",
    donem: "19. Yüzyıl",
    tescil: "2. Derece",
    mulkiyet: "Vakıf",
    koruma: "İyi",
    durum: "Onaylı",
    malzeme: "Taş, Tuğla",
    islevOzgun: "Cami",
    islevGuncel: "Cami",
    mahalle: "Hayrettinpaşa",
    lat: 39.3178, lng: 26.6941,
    aciklama: "II. Abdülhamit dönemine ait Osmanlı dini mimari örneği. Geleneksel cami planını bölgenin yerel taş işçiliğiyle harmanlayan yapı, sağlam korunma durumunu korumaktadır.",
    fotoBg: "linear-gradient(160deg,#1a1a2a,#2a2a4a)",
    fotoUrl: "images/AYV-0003.jpg"
  },
  {
    id: "AYV-0004",
    ad: "Kemalpaşa Konağı",
    tur: "Sivil Mimari",
    donem: "18. Yüzyıl",
    tescil: "1. Derece",
    mulkiyet: "Özel",
    koruma: "Kötü",
    durum: "Onaylı",
    malzeme: "Ahşap, Taş",
    islevOzgun: "Konut",
    islevGuncel: "Kullanım Dışı",
    mahalle: "Kemalpaşa",
    lat: 39.3212, lng: 26.6958,
    aciklama: "Geç 18. yüzyıla tarihlenen iki katlı Rum konağı. Çıkmalı cephe düzeni ve ahşap işçiliğiyle Ayvalık sivil mimarisinin önemli örneklerinden biridir. Acil müdahale gerekmektedir.",
    fotoBg: "linear-gradient(160deg,#2a1a10,#4a2a10)",
    fotoUrl: "images/AYV-0004.jpg"
  },
  {
    id: "AYV-0005",
    ad: "Hayrettinpaşa Çeşmesi",
    tur: "Su Yapısı",
    donem: "18. Yüzyıl",
    tescil: "2. Derece",
    mulkiyet: "Kamu",
    koruma: "Orta",
    durum: "Onaylı",
    malzeme: "Mermer, Taş",
    islevOzgun: "Çeşme",
    islevGuncel: "Çeşme",
    mahalle: "Hayrettinpaşa",
    lat: 39.3188, lng: 26.6978,
    aciklama: "Kitabeli Osmanlı çeşmesi. Mermer ayna taşı ve yanlarındaki kabartma süslemesiyle dönemin su yapısı sanatını yansıtmaktadır.",
    fotoBg: "linear-gradient(160deg,#10202a,#1a3a4a)",
    fotoUrl: "images/AYV-0005.jpg"
  },
  {
    id: "AYV-0006",
    ad: "Eski Zeytinyağı Fabrikası",
    tur: "Ticari Yapı",
    donem: "20. Yüzyıl Başı",
    tescil: "Tescil Önerisi",
    mulkiyet: "Özel",
    koruma: "Orta",
    durum: "Taslak",
    malzeme: "Tuğla, Demir",
    islevOzgun: "Fabrika",
    islevGuncel: "Depo",
    mahalle: "Liman",
    lat: 39.3168, lng: 26.6995,
    aciklama: "Ayvalık'ın zeytinyağı üretimiyle özdeşleşen endüstri mirasının somut kanıtı. UNESCO geçici listesindeki 'Ayvalık Endüstri Mirası' başvurusunun temel bileşenlerinden biridir.",
    fotoBg: "linear-gradient(160deg,#202020,#383828)",
    fotoUrl: "images/AYV-0006.jpg"
  },
  {
    id: "AYV-0007",
    ad: "Taksiyarhis Anıt Müzesi",
    tur: "Kamusal Yapı",
    donem: "19. Yüzyıl",
    tescil: "1. Derece",
    mulkiyet: "Kamu",
    koruma: "İyi",
    durum: "Onaylı",
    malzeme: "Taş",
    islevOzgun: "Kilise",
    islevGuncel: "Müze",
    mahalle: "Cumhuriyet",
    lat: 39.3199, lng: 26.6948,
    aciklama: "Ayvalık'ın ilk kilisesi olan yapı, çeşitli dönemlerde onarılmış ve değiştirilmiştir. 2012'de restore edilen yapı, 2013'ten bu yana Taksiyarhis Anıt Müzesi olarak ziyaretçilere açıktır.",
    fotoBg: "linear-gradient(160deg,#1a1a28,#2a2a40)",
    fotoUrl: "images/AYV-0007.jpg"
  },
  {
    id: "AYV-0008",
    ad: "Liman Hanı",
    tur: "Ticari Yapı",
    donem: "19. Yüzyıl",
    tescil: "2. Derece",
    mulkiyet: "Özel",
    koruma: "Kötü",
    durum: "Taslak",
    malzeme: "Taş, Ahşap",
    islevOzgun: "Han",
    islevGuncel: "Kullanım Dışı",
    mahalle: "Liman",
    lat: 39.3172, lng: 26.6982,
    aciklama: "Ticaret limanına yakın konumuyla Ayvalık'ın tarihsel ticari önemine tanıklık eden han yapısı. Yapısal bozulmalar devam etmekte, acil konsolidasyon gerektirmektedir.",
    fotoBg: "linear-gradient(160deg,#281818,#402020)",
    fotoUrl: "images/AYV-0008.jpg"
  }
];
